# Generated by Django 4.2 on 2024-03-03 18:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_storedfile_delete_csvfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='storedfile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('processing', 'Processing'), ('done', 'Done')], default='pending', max_length=10),
        ),
    ]
